version: '3.8'

services:

  account-portal:
    container_name: account_portal
    image: datpd57/account_portal:1.0
    build:
      context: .
      dockerfile: account-portal.dockerfile
    env_file: .env
    ports:
      - "8020:8020"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - API_DOMAIN_ADDRESS=${API_DOMAIN_ADDRESS}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    external:
      name: itravel-network