version: '3.8'

services:

  auth-portal:
    container_name: auth_portal
    image: datpd57/auth_portal:1.0
    build:
      context: .
      dockerfile: auth-portal.dockerfile
    ports:
      - "8011:8011"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - API_DOMAIN_ADDRESS=${API_DOMAIN_ADDRESS}
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    external:
      name: itravel-network